# Version of docker compose to use
version: "3.8"
services:
  nodejs:
    build: ./nodejs
    container_name: api_c
    ports:
      - '4000:4000' 
    volumes:
      - ./nodejs:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '5173:3000'
    stdin_open: true
    tty: true